name: learn-github-actions
on: 
 push:
  branches: [ development ]
  paths:
    - '**.cs'
    - '**.csproj'

jobs:
 build:
  runs-on: ubuntu-latest   # alternate runner OS is: ubuntu-latest
  env:
      RUNNER_DEBUG: 1
      URL_DYNAMICS: 'https://pruebasminsait.crm4.dynamics.com'
      USER_DYNAMICS: 'rlgalvan@tecxrm.com'
      PASS_DYNAMICS: 'Indra2507'
      CLIENT_ID: 'd4416ad8-8ed5-4776-95b7-80985180bcc0'
      TENANT_ID: 'ec6b17bb-11d0-4195-abd0-521c69a5d1fd'
      SOLUTION_NAME: 'DevPruebaSan'
      SOLUTION_EXPORTED_FOLDER: 'out/exported/'
      SOLUTION_FOLDER: 'out/solutions/'
      SOLUTION_TARGET_FOLDER: 'solutions/'
      URL_DYNAMICS_PRODUCTION: 'https://org392b3613.crm4.dynamics.com'
      USER_DYNAMICS_PRODUCTION: 'TestTestSNT@TESTMINDevOps.onmicrosoft.com'
      PASS_DYNAMICS_PRODUCTION: 'TrialSNT0609'
      URL_SONAR_QAT: 'https://qatsonarqubeint.mx.corp/'
      URL_SONAR_PANDORA: 'http://sonar.pro.pandora.mx.corp/'
      URL_SONAR_WAS: 'http://wasatdipvlmx01.mx.corp:9000/'
      DOTNET_VERSION: '5.0.301' # The .NET SDK version to use
    
  steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Test
        run: dotnet test --no-restore --verbosity normal
